// Layer-shell wrapper for FLTK Wayland panel
// Creates a layer-shell surface and manages rendering

#ifndef LAYER_SHELL_H
#define LAYER_SHELL_H

#include <wayland-client.h>
#include <cairo/cairo.h>

// Layer shell protocol interfaces (manually defined)
// These would normally be generated by wayland-scanner

// Anchor bits
#define ANCHOR_TOP     (1 << 0)
#define ANCHOR_BOTTOM  (1 << 1)
#define ANCHOR_LEFT    (1 << 2)
#define ANCHOR_RIGHT   (1 << 3)

// Keyboard interactivity modes
#define KEYBOARD_NONE      0
#define KEYBOARD_EXCLUSIVE 1
#define KEYBOARD_ON_DEMAND 2

// Layer values
#define LAYER_BACKGROUND 0
#define LAYER_BOTTOM     1
#define LAYER_TOP        2
#define LAYER_OVERLAY    3

struct LayerShellConfig {
    int width;          // 0 = full width
    int height;         // panel height
    int anchor;         // ANCHOR_* bitmask
    int exclusive_zone; // space to reserve
    int layer;          // LAYER_*
    const char *name_space;
};

// Opaque types for protocol objects
struct wl_surface;
struct wl_output;

class LayerSurface {
public:
    LayerSurface();
    ~LayerSurface();

    // Initialize layer-shell from Wayland registry
    bool init(struct wl_display *display);

    // Configure the layer surface
    void configure(const LayerShellConfig &config);

    // Create/update the buffer
    void update_buffer(cairo_t *cr, int width, int height);

    // Get the surface for rendering
    struct wl_surface *get_surface() { return surface; }

    // Check if surface is configured
    bool is_configured() const { return configured; }

    // Get current dimensions
    int get_width() const { return width; }
    int get_height() const { return height; }

private:
    struct wl_display *display = nullptr;
    struct wl_surface *surface = nullptr;
    struct wl_compositor *compositor = nullptr;
    struct wl_shm *shm = nullptr;

    // Layer shell objects (opaque pointers)
    void *layer_shell = nullptr;
    void *layer_surface = nullptr;

    // SHM buffer
    struct wl_buffer *buffer = nullptr;
    void *buffer_data = nullptr;
    int buffer_fd = -1;
    int width = 0;
    int height = 0;
    bool configured = false;

    // Cairo surface for rendering
    cairo_surface_t *cairo_surface = nullptr;

    // Create SHM pool and buffer
    bool create_buffer(int w, int h);

    // Destroy current buffer
    void destroy_buffer();
};

#endif // LAYER_SHELL_H
