#!/usr/bin/env python3
import os
import time
import subprocess
import ast
import re

HOME = os.environ.get("HOME", "/tmp")

# Paths
NOCTALIA_CONFIG = os.path.join(HOME, ".config/noctalia/config.toml")
OCWS_SETTINGS = os.path.join(HOME, ".config/ocws/settings.config")
SFWBAR_WIDGET = os.path.join(HOME, ".config/ocws/widgets/core/dock-apps.widget")
CRYSTAL_CONFIG = os.path.join(HOME, ".config/crystal-dock/panel_1.conf")
GSETTINGS_CMD = ["gsettings", "get", "org.gnome.shell", "favorite-apps"]

# Items that are structural in docks rather than actual apps
STRUCTURAL_APPS = {"show-desktop", "separator", "lxqt-lockscreen", "lxqt-logout"}

def clean_apps(apps):
    """Clean the app list of .desktop extensions and structural pseudo-apps."""
    cleaned = []
    for a in apps:
        base = a.replace('.desktop', '')
        if base not in STRUCTURAL_APPS and base.strip():
            cleaned.append(base)
    return cleaned

# --- DMS (GNOME gsettings) ---
def get_dms():
    try:
        output = subprocess.check_output(GSETTINGS_CMD, text=True).strip()
        apps = ast.literal_eval(output)
        return clean_apps(apps)
    except Exception as e:
        print(f"Error reading DMS: {e}")
        return []

def set_dms(apps):
    desktop_apps = [f"{a}.desktop" if not a.endswith('.desktop') else a for a in apps]
    val = str(desktop_apps).replace("'", '"')
    subprocess.run(["gsettings", "set", "org.gnome.shell", "favorite-apps", val])

# --- Noctalia ---
def get_noctalia():
    if not os.path.exists(NOCTALIA_CONFIG): return []
    with open(NOCTALIA_CONFIG, "r", encoding="utf-8") as f:
        content = f.read()
    match = re.search(r'^\s*pinned\s*=\s*(\[[^\]]*\])', content, re.MULTILINE)
    if match:
        try: return clean_apps(ast.literal_eval(match.group(1)))
        except: return []
    return []

def set_noctalia(apps):
    if not os.path.exists(NOCTALIA_CONFIG): return
    with open(NOCTALIA_CONFIG, "r", encoding="utf-8") as f:
        content = f.read()
    val = str(apps).replace("'", '"')
    if re.search(r'^\s*pinned\s*=', content, re.MULTILINE):
        new_content = re.sub(r'^\s*pinned\s*=.*$', f'pinned = {val}', content, flags=re.MULTILINE)
    else:
        new_content = re.sub(r'^\[dock\]', f'[dock]\npinned = {val}', content, flags=re.MULTILINE)
    with open(NOCTALIA_CONFIG, "w", encoding="utf-8") as f:
        f.write(new_content)

# --- Crystal Dock ---
def get_crystaldock():
    if not os.path.exists(CRYSTAL_CONFIG): return []
    with open(CRYSTAL_CONFIG, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("launchers="):
                val = line.split("=", 1)[1].strip().strip('"')
                apps = val.split(";")
                return clean_apps(apps)
    return []

def set_crystaldock(apps):
    if not os.path.exists(CRYSTAL_CONFIG): return
    with open(CRYSTAL_CONFIG, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Preserve layout: show-desktop at start, and standard system actions at end
    new_launchers = "show-desktop;" + ";".join(apps) + ";separator;lxqt-lockscreen;lxqt-logout;separator"
    new_content = re.sub(r'^launchers=.*$', f'launchers="{new_launchers}"', content, flags=re.MULTILINE)
    
    with open(CRYSTAL_CONFIG, "w", encoding="utf-8") as f:
        f.write(new_content)

# --- SFWBar (OCWS) ---
def get_sfwbar():
    if not os.path.exists(OCWS_SETTINGS): return []
    with open(OCWS_SETTINGS, "r", encoding="utf-8") as f:
        for line in f:
            match = re.search(r'Set\s+OCWS_DOCK_APPS\s*=\s*"([^"]*)"', line)
            if match:
                apps = match.group(1).split(",")
                return clean_apps(apps)
    return []

def render_sfwbar_widget(apps):
    """Auto-generates the SFWBar dock widget file with new buttons."""
    lines = ["#Api2", "# dock-apps.widget \u2014 Auto-generated by dock-sync.py\n"]
    
    for app in apps:
        app_clean = app.strip()
        if not app_clean: continue
        
        # Heuristics for pretty tooltips
        tooltip = app_clean.capitalize().replace('-', ' ')
        
        block = f"""# --- {tooltip} ---
button {{
  style = "dock_app"
  tooltip = "{tooltip}"
  action = Exec("{app_clean}")
  image {{
    icon = "{app_clean}"
    css = "* {{ min-width: 32px; min-height: 32px; }}"
  }}
}}
"""
        lines.append(block)
    
    # Add separator and settings icon at the end
    lines.append("""# --- Separator ---
label {
  style = "dock_sep"
  value = "|"
}

# --- Settings ---
button {
  style = "dock_app"
  tooltip = "OCWS Settings"
  action = Exec("ocws-settings")
  image {
    icon = "preferences-desktop-symbolic"
    css = "* { min-width: 32px; min-height: 32px; }"
  }
}""")
    
    if os.path.exists(os.path.dirname(SFWBAR_WIDGET)):
        with open(SFWBAR_WIDGET, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

def set_sfwbar(apps):
    if not os.path.exists(OCWS_SETTINGS): return
    with open(OCWS_SETTINGS, "r", encoding="utf-8") as f:
        content = f.read()
    
    val = ",".join(apps)
    new_content = re.sub(r'(Set\s+OCWS_DOCK_APPS\s*=\s*)"[^"]*"', rf'\g<1>"{val}"', content)
    
    with open(OCWS_SETTINGS, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    # Also regenerate the widget file
    render_sfwbar_widget(apps)

# --- Main Engine ---
def sync_all(apps):
    set_dms(apps)
    set_noctalia(apps)
    set_crystaldock(apps)
    set_sfwbar(apps)

def get_mtime(path):
    return os.path.getmtime(path) if os.path.exists(path) else 0

def main():
    print("[Dock Sync] 4-Way Bi-Directional Sync Started...")
    
    # 1. Initial Sync (Master: DMS)
    apps = get_dms()
    print(f"[Dock Sync] Initial Master Apps: {apps}")
    sync_all(apps)
    
    last_apps = apps
    
    last_mtimes = {
        "noctalia": get_mtime(NOCTALIA_CONFIG),
        "crystal": get_mtime(CRYSTAL_CONFIG),
        "sfwbar": get_mtime(OCWS_SETTINGS)
    }
    
    print("[Dock Sync] Listening for changes across all 4 shell layers...")
    
    while True:
        time.sleep(1.5)
        
        # Check DMS
        dms_apps = get_dms()
        if dms_apps != last_apps:
            print(f"[Dock Sync] DMS changed! Syncing: {dms_apps}")
            sync_all(dms_apps)
            last_apps = dms_apps
            last_mtimes["noctalia"] = get_mtime(NOCTALIA_CONFIG)
            last_mtimes["crystal"] = get_mtime(CRYSTAL_CONFIG)
            last_mtimes["sfwbar"] = get_mtime(OCWS_SETTINGS)
            continue
            
        # Check Noctalia
        m_noct = get_mtime(NOCTALIA_CONFIG)
        if m_noct > last_mtimes["noctalia"]:
            last_mtimes["noctalia"] = m_noct
            n_apps = get_noctalia()
            if n_apps != last_apps:
                print(f"[Dock Sync] Noctalia changed! Syncing: {n_apps}")
                sync_all(n_apps)
                last_apps = n_apps
                last_mtimes["crystal"] = get_mtime(CRYSTAL_CONFIG)
                last_mtimes["sfwbar"] = get_mtime(OCWS_SETTINGS)
                continue
                
        # Check Crystal
        m_crys = get_mtime(CRYSTAL_CONFIG)
        if m_crys > last_mtimes["crystal"]:
            last_mtimes["crystal"] = m_crys
            c_apps = get_crystaldock()
            if c_apps != last_apps:
                print(f"[Dock Sync] Crystal Dock changed! Syncing: {c_apps}")
                sync_all(c_apps)
                last_apps = c_apps
                last_mtimes["noctalia"] = get_mtime(NOCTALIA_CONFIG)
                last_mtimes["sfwbar"] = get_mtime(OCWS_SETTINGS)
                continue

        # Check SFWBar
        m_sfw = get_mtime(OCWS_SETTINGS)
        if m_sfw > last_mtimes["sfwbar"]:
            last_mtimes["sfwbar"] = m_sfw
            s_apps = get_sfwbar()
            if s_apps != last_apps:
                print(f"[Dock Sync] SFWBar changed! Syncing: {s_apps}")
                sync_all(s_apps)
                last_apps = s_apps
                last_mtimes["noctalia"] = get_mtime(NOCTALIA_CONFIG)
                last_mtimes["crystal"] = get_mtime(CRYSTAL_CONFIG)
                continue

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("[Dock Sync] Stopped.")
