#pragma once
// wayland_panel.h - Raw Wayland + wlr-layer-shell panel surface manager
//
// This module handles all Wayland protocol interaction:
//   - Connects to the compositor
//   - Binds wl_compositor, wl_shm, zwlr_layer_shell_v1
//   - Creates a layer surface anchored to the top edge
//   - Manages SHM double-buffered pixel buffers
//   - Dispatches frame callbacks for smooth rendering
//   - Forwards pointer events to the application

#include <wayland-client.h>
#include <functional>
#include <cstdint>
#include <string>
#include <vector>

// Forward-declare protocol types (generated by wayland-scanner)
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;
struct zwlr_foreign_toplevel_manager_v1;
struct zwlr_foreign_toplevel_handle_v1;

class WaylandPanel;

// Information about a running window/app
struct WindowInfo {
    WaylandPanel* panel = nullptr;
    struct zwlr_foreign_toplevel_handle_v1* handle = nullptr;
    std::string title;
    std::string app_id;
    bool maximized = false;
    bool minimized = false;
    bool activated = false;
};

// Forward-declare protocol types (generated by wayland-scanner)
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;

// Render callback: receives (pixel_buffer, width, height, stride_in_bytes)
using RenderCallback = std::function<void(uint32_t* buffer, int w, int h, int stride)>;

// Click callback: receives (x, y, button)
using ClickCallback = std::function<void(int x, int y, uint32_t button)>;

class WaylandPanel {
public:
    // Panel configuration
    struct Config {
        int height = 32;                // Panel height in pixels
        bool anchor_top = true;         // true=top edge, false=bottom edge
        const char* namespace_name = "fltk-panel"; // Layer surface namespace
    };

    explicit WaylandPanel(const Config& cfg);
    ~WaylandPanel();

    // Initialize the Wayland connection and layer surface. Returns true on success.
    bool init();

    // Run the main event loop (blocks until close).
    void run();

    // Request a redraw on the next frame.
    void request_redraw();

    // Set callback for rendering. Called each frame with the SHM pixel buffer.
    void set_render_callback(RenderCallback cb) { render_cb_ = std::move(cb); }

    // Set callback for pointer clicks.
    void set_click_callback(ClickCallback cb) { click_cb_ = std::move(cb); }

    // Current panel dimensions (set by compositor in configure event).
    int width() const { return width_; }
    int height() const { return height_; }

    // Should the panel keep running?
    bool running() const { return running_; }

    // Dock/Window Switcher API
    const std::vector<WindowInfo*>& windows() const { return windows_; }
    void activate_window(WindowInfo* win);
    void close_window(WindowInfo* win);

private:
    // --- Wayland globals ---
    struct wl_display*    display_  = nullptr;
    struct wl_registry*   registry_ = nullptr;
    struct wl_compositor* compositor_ = nullptr;
    struct wl_shm*        shm_      = nullptr;
    struct wl_seat*       seat_     = nullptr;
    struct wl_pointer*    pointer_  = nullptr;
    struct wl_output*     output_   = nullptr;
    struct zwlr_layer_shell_v1*   layer_shell_   = nullptr;
    struct zwlr_foreign_toplevel_manager_v1* toplevel_manager_ = nullptr;

    // --- Surface objects ---
    struct wl_surface*             surface_       = nullptr;
    struct zwlr_layer_surface_v1*  layer_surface_ = nullptr;
    struct wl_callback*            frame_cb_      = nullptr;

    // --- Tracked Windows ---
    std::vector<WindowInfo*> windows_;

    // --- SHM buffer ---
    struct wl_buffer* buffer_     = nullptr;
    uint32_t*         pixel_data_ = nullptr;
    int               shm_fd_    = -1;
    size_t            shm_size_  = 0;

    // --- State ---
    Config config_;
    int    width_       = 0;
    int    height_      = 0;
    bool   configured_  = false;
    bool   running_     = true;
    bool   needs_redraw_ = true;

    // Pointer state
    int pointer_x_ = 0;
    int pointer_y_ = 0;

    // Callbacks
    RenderCallback render_cb_;
    ClickCallback  click_cb_;

    // --- Internal methods ---
    bool create_shm_buffer();
    void destroy_shm_buffer();
    void render_frame();
    void schedule_frame();

public:
    // --- Wayland listener callbacks (static, forwarding to instance) ---
    static void registry_global(void* data, struct wl_registry* reg, uint32_t name,
                                const char* interface, uint32_t version);
    static void registry_global_remove(void* data, struct wl_registry* reg, uint32_t name);

    static void layer_surface_configure(void* data, struct zwlr_layer_surface_v1* surface,
                                         uint32_t serial, uint32_t w, uint32_t h);
    static void layer_surface_closed(void* data, struct zwlr_layer_surface_v1* surface);

    static void frame_done(void* data, struct wl_callback* cb, uint32_t time);

    static void pointer_enter(void* data, struct wl_pointer* ptr, uint32_t serial,
                              struct wl_surface* surface, wl_fixed_t sx, wl_fixed_t sy);
    static void pointer_leave(void* data, struct wl_pointer* ptr, uint32_t serial,
                              struct wl_surface* surface);
    static void pointer_motion(void* data, struct wl_pointer* ptr, uint32_t time,
                               wl_fixed_t sx, wl_fixed_t sy);
    static void pointer_button(void* data, struct wl_pointer* ptr, uint32_t serial,
                               uint32_t time, uint32_t button, uint32_t state);
    static void pointer_axis(void* data, struct wl_pointer* ptr, uint32_t time,
                             uint32_t axis, wl_fixed_t value);

    static void seat_capabilities(void* data, struct wl_seat* seat, uint32_t caps);
    static void seat_name(void* data, struct wl_seat* seat, const char* name);

    // Foreign toplevel management callbacks
    static void toplevel_manager_toplevel(void* data, struct zwlr_foreign_toplevel_manager_v1* manager, struct zwlr_foreign_toplevel_handle_v1* toplevel);
    static void toplevel_manager_finished(void* data, struct zwlr_foreign_toplevel_manager_v1* manager);

    static void toplevel_handle_title(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, const char* title);
    static void toplevel_handle_app_id(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, const char* app_id);
    static void toplevel_handle_output_enter(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, struct wl_output* output);
    static void toplevel_handle_output_leave(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, struct wl_output* output);
    static void toplevel_handle_state(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, struct wl_array* state);
    static void toplevel_handle_done(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel);
    static void toplevel_handle_closed(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel);
    static void toplevel_handle_parent(void* data, struct zwlr_foreign_toplevel_handle_v1* toplevel, struct zwlr_foreign_toplevel_handle_v1* parent);
};
