[General]
activeIndicatorColor=#ff8c00
activeIndicatorColorMetal2D=#ffbf00
backgroundColor=#6b638abd
backgroundColorMetal2D=#ad7381a6
borderColor=#99addd
bouncingLauncherIcon=false
firstRunWindowCountIndicator=false
floatingMargin=6
fontFamily=FiraCode Nerd Font
fontSize=11
inactiveIndicatorColor=#008b8b
inactiveIndicatorColorMetal2D=#00ffff
iconTheme=Papirus-Dark
maximumIconSize=48
minimumIconSize=32
panelStyle=4
showTooltip=true
spacingFactor=0.5
tooltipFontSize=24
zoomingAnimationSpeed=0

[Application%20Menu]
backgroundAlpha=0.8
fontFamily=FiraCode Nerd Font
fontSize=14
label=Applications

[Clock]
fontFamily=FiraCode Nerd Font
fontScaleFactor=1
use24HourClock=true
